import Head from 'next/head';
import { Card } from '../components/card';
import { getLayout, NextPageWithLayout } from '../components/layout';

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Chain Me Up - Adult Entertainment on Chain (get it?)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card
        isVerified
        name="Aylin Bülbül"
        tag="aaylinbulbull"
        content="person-01"
        description="Andy took this picture right when I step on something, hahaha that was funny. Or was it? ✈️🌍"
      />
      <Card
        isVerified
        name="Dr J.Joy"
        tag="dr.jjoy"
        content="person-02"
        description="It's too cold for me during winter. I'd rather be home."
      />
      <Card
        isVerified
        name="Hisu lee"
        tag="hisulee"
        content="person-03"
        description="Soap is like a box of chocolates, you never know what you're going to get."
      />
      <Card
        isVerified
        name="Maria Silva"
        tag="silva"
        content="person-04"
        description="Sometimes I forget what I was thinking about... ☀️🏖️🩴"
      />
      <Card
        isVerified
        name="Alvin Bueno"
        tag="bueno.a"
        content="person-05"
        description="New hat! Who dis? 👒"
      />
    </>
  );
};

Home.getLayout = getLayout;

export default Home;
