import type { NextPage } from 'next';
import Head from 'next/head';
import { Card } from '../components/card';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chain Me Up - Adult Entertainment on Chain (get it?)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card
        isVerified
        name="Surfer Claire"
        tag="surferclaire"
        description="New surf top! I love the long sleeve top for surfing as it protects my skin from getting a rash on the board and also provides and SPF protection from the sun ☀️ win win 🥇 if you ask me!"
      />
      <Card
        isVerified
        name="Surfer Claire"
        tag="surferclaire"
        description="New surf top! I love the long sleeve top for surfing as it protects my skin from getting a rash on the board and also provides and SPF protection from the sun ☀️ win win 🥇 if you ask me!"
      />
      <Card
        isVerified
        name="Surfer Claire"
        tag="surferclaire"
        description="New surf top! I love the long sleeve top for surfing as it protects my skin from getting a rash on the board and also provides and SPF protection from the sun ☀️ win win 🥇 if you ask me!"
      />
      <Card
        isVerified
        name="Surfer Claire"
        tag="surferclaire"
        description="New surf top! I love the long sleeve top for surfing as it protects my skin from getting a rash on the board and also provides and SPF protection from the sun ☀️ win win 🥇 if you ask me!"
      />
      <Card
        isVerified
        name="Surfer Claire"
        tag="surferclaire"
        description="New surf top! I love the long sleeve top for surfing as it protects my skin from getting a rash on the board and also provides and SPF protection from the sun ☀️ win win 🥇 if you ask me!"
      />
    </>
  );
};

export default Home;
